### ISSUE TITLE
JMX

### ISSUE THREAD

**Issue by fatlazycat** [ches/docker-kafka#1]
Hi, how do you connect jconsole ?

I'm trying on the equivalent of $KAFKA_IP:7203

But it just never seems to connect.

Have I got the wrong IP ?

Thanks

**Comment by ches** [comment]
I know this was awhile ago, but you're right that JMX wasn't very usable from outside—if you're still working with this image, have a look at d4d974e8dcf9a2b which is now in `ches/kafka:0.8.2.1` and see if that covers all the configurability you need.
