### ISSUE TITLE
Fix KAFKA_AUTO_CREATE_TOPICS_ENABLE

### ISSUE THREAD

**Issue by bluepuma77** [ches/docker-kafka#43]
I think both should be with _ENABLE as docs (parameter) and template have it.

start.sh
```-e "s|{{KAFKA_AUTO_CREATE_TOPICS_ENABLE}}|${KAFKA_AUTO_CREATE_TOPICS:-true}|g" \```

**Comment by ches** [comment]
Doh, sorry for that oversight and thanks for reporting!

The fix will be in the `latest` tag build in a few minutes, and I'll make a release for Kafka 0.10.2.1 shortly including it as well.
