### ISSUE TITLE
Docker image differs

### ISSUE THREAD

**Issue by Bellovitello** [ches/docker-kafka#56]
Hi Ches,
I've tried your docker image from docker hub and I have problem with _server.properties_ file. The file in github is correct but in the docker image there are some important missing properties like _message.max.bytes_ and _replica.fetch.max.bytes_ and some others.

I have to rebuild the image to make it works fine.

**Comment by ches** [comment]
Hi, please let me know specific steps to reproduce the issue you're having—image version that you're running, commands for how you're running it, etc. Is Kafka actually failing to run, or you're just not able to set options you need?

This image is an Automated Build, Docker Hub builds it straight from the source in GitHub, so there should not be any discrepancy. But the two particular settings that you mentioned were added in #50 and don't have a tagged version released yet, you'd only get them from the `latest` tag (which is Kafka 0.10.2.1 at this point, I need to get caught up).

**Comment by Bellovitello** [comment]
Hi, thanks for your reply. Kafka is running I was only not able to set up the option _message.max.byte_ because it is not present in the template file.
I now understand: I'm using 0.10.2.1 not the lates, but I'm looking at latest git version.

Thanks for your explanation, it's not a bug.
